name: Update Formula

on:
  workflow_dispatch:
    types: [update-formula]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update formula version and checksum
        run: |
          sed -i 's/version ".*"/version "${{ github.event.client_payload.version }}"/' Formula/git-intent.rb
          sed -i 's/sha256 ".*"/sha256 "${{ github.event.client_payload.sha256 }}"/' Formula/git-intent.rb

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update git-intent to v${{ github.event.client_payload.version }}"
          title: "Update git-intent to v${{ github.event.client_payload.version }}"
          body: |
            Updates git-intent to v${{ github.event.client_payload.version }}

            - Version: ${{ github.event.client_payload.version }}
            - SHA256: ${{ github.event.client_payload.sha256 }}
          branch: update-git-intent-v${{ github.event.client_payload.version }}
          delete-branch: true
